# Como base de la creación de mi nueva imagen tomo la versión más reciente de ubuntu
FROM ubuntu:latest
# En mi versión modificada de ubuntu habrá un archivo llamado `hola-mundo.txt` vacío
RUN touch /usr/src/hola-mundo.txt
# Aquí terminan las capas de modificación de la imagen original de ubuntu